# coding=utf8

from bs4 import BeautifulSoup
import requests

url='http://biz.click.ganji.com/bizClick?url=pZwY0jCfsvFJshI6UhGGshPfUiqJpy7JIitQPj0dPHnLP1DvXaOCIAd0njTQPjuKnDNYnHuAENckwNmQEW6DE1ParHmkwbwAnD7awbR0njTQnWnvrjmLnjbkPHbQnWEQPHEQrjE3ndkknjDVgjTknHc3PH9zPWn1PdkknjDQP7kknjDQPj0dPHnLP1DvgjTknHDQr7kknjDQnHR0njTQnHE3gjTknHDzgjTknHDYPWTdPHNLrjE1PW-0njTQnRkknjDQn170njTQmh-buA-8udkknjDQgjTknyI6UhGGmvqVgLKMgjTknHK0njTQnWnvrjmLnjbkPHbQnWEQPHEQrjE3ndkknjDkgjTknHDQnz3znjD8PHN8nWndgjTknNdfXh-_UADfPi3kca6gpyObULI1cDONcjDksWTec7I5R1mY2iKK0ZK_uRI-mbVGIatdn108n1m92DVcRDdnsaK_pyV-cDI-mvVf2iKjpZFfUyNfPjb8na3zPWc1sWDQnBKHmyu60hbfPHnLsWnvgjTknHN3P7kknjDVnRkknjDVnRkknj7jpZFfUyR0njTQPjcYryczujNVmWD1PBYYrj9OsHbYuAcVnHnzuhEdPyDLPh7b&v=2'
wb_data = requests.get(url)
print(wb_data.url)
_id = wb_data.url.split('/')[-1].split('x.')[0]
print('id: ', _id)
